### ISSUE TITLE
Referent_ID weirdness

### ISSUE THREAD

**Issue by elizabethyalkut** [Brown-University-Library/disa_dj_project#182]
While working on the map -- using data from Khanh so the lat/long info corresponds to the correct place name -- I'm trying to link to a person who is recorded at the given point. But the "Referent_ID" I have access to doesn't match what I expect.

For example: in the data provided, George Weymouth has the Referent_ID 3002. The URL `/redesign_citations/996/#/1242/3002` lets an RA _edit_ George Weymouth. But the URL `/people/3002` is for a totally different, unrelated person. George Weymouth is viewable at `/people/2998/`. I have no access to this uuid atm; what DB field needs to be added to the geojson Feature so I link the correct person?

**Comment by birkin** [comment]
@elizabethyalkut -- not an answer (I'll get you one), but some context... When a person-mentioned-in-a-record is added, that person is added to a Referent table. 

IIRC, there is before-my-time code that _also_ attempts to populate a People table. I don't remember the logic of the code, I recall it _very-mildly_ attempts to solve the "This referent is the same as that referent." problem -- maybe via similar name and dob? Because it's not reliable, I've strived to not advertise the People table data. But there is an existing People page that I think the research-assistants still find useful. (I've long wanted to replace that with a listing of Referents.)

Ok, context done; I'll look at your actual question.
