### ISSUE TITLE
Add option to main navigation to view tabulator in new form

### ISSUE THREAD

**Issue by ashleychampagne** [Brown-University-Library/disa_dj_project#89]

**Comment by birkin** [comment]
Implemented in the `new_flow` branch. I'll not yet close this because:
- I'd like to get an ok from others on the dev-team first (y'all might prefer the 'Browse' link in a different position than first).
- In order to get it to fit, I had to change the logged-in indicator, eg `(Wecome Birkin)` -- to just `(Birkin)`. I liked the "Welcome"; @bentbul might you want to take a crack at how to get that back in and still fit?

**Comment by ashleychampagne** [comment]
This is fixed.
